NUTRIENT_UNITS = {
    "Energy": "kcal",
    "Protein": "g",
    "Total lipid (fat)": "g",
    "Carbohydrate, by difference": "g",
    "Fiber, total dietary": "g",
    "Sugars, total including NLEA": "g",
    "Fatty acids, total saturated": "g",
    "Fatty acids, total monounsaturated": "g",
    "Fatty acids, total polyunsaturated": "g",
    "Fatty acids, total trans": "g",
    "Cholesterol": "mg",
    "Sodium, Na": "mg",
    "Potassium, K": "mg",
    "Calcium, Ca": "mg",
    "Iron, Fe": "mg",
    "Magnesium, Mg": "mg",
    "Phosphorus, P": "mg",
    "Zinc, Zn": "mg",
    "Copper, Cu": "mg",
    "Manganese, Mn": "mg",
    "Selenium, Se": "μg",
    "Vitamin C, total ascorbic acid": "mg",
    "Thiamin": "mg",
    "Riboflavin": "mg",
    "Niacin": "mg",
    "Pantothenic acid": "mg",
    "Vitamin B-6": "mg",
    "Folate, total": "μg",
    "Folic acid": "μg",
    "Folate, food": "μg",
    "Folate, DFE": "μg",
    "Choline, total": "mg",
    "Vitamin B-12": "μg",
    "Vitamin A, RAE": "μg",
    "Retinol": "μg",
    "Carotene, beta": "μg",
    "Carotene, alpha": "μg",
    "Cryptoxanthin, beta": "μg",
    "Lycopene": "μg",
    "Lutein + zeaxanthin": "μg",
    "Vitamin E (alpha-tocopherol)": "mg",
    "Vitamin D (D2 + D3)": "μg",
    "Vitamin K (phylloquinone)": "μg",
    "Water": "g",
    "Ash": "g"
}